version: '3.8'
services:
  database:
    image: postgis/postgis:14-master
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  
  # ---------- TAMBAHAN SERVICE APLIKASI WEB DI SINI ----------
  web:
    build: . # Tetapkan build context di direktori utama
    environment:
      - FLASK_APP=app.py # Tambahkan environment variable Flask
      - FLASK_ENV=development
    ports:
      - "8000:8000"
    # Tambahkan volume agar Docker Compose dapat melihat perubahan kode Anda tanpa rebuild total
    volumes:
      - ./api_ingestion:/app
    depends_on:
      - database
